version: '3.8'

services:
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build: .
    # Если на сервере — используй gunicorn, для тестов можно оставить runserver
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_static:/app/staticfiles
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - database

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_static:/app/staticfiles:ro
      # Пробрасываем сертификаты Let's Encrypt
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django_app

volumes:
  static_static:
  postgres_data: